# Generated by Django 4.0.3 on 2022-04-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='B_PHARMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_NO', models.IntegerField()),
                ('Course', models.CharField(max_length=70)),
                ('STUDENT_ID', models.IntegerField()),
                ('Student_roll_no', models.IntegerField()),
                ('NAME', models.CharField(max_length=70)),
                ('NAME_OF_ADVISOR', models.CharField(max_length=70)),
                ('MAIL', models.CharField(max_length=70)),
                ('APPROVED_BY', models.CharField(max_length=70)),
                ('SESSION', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='BSC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_NO', models.IntegerField()),
                ('Course', models.CharField(max_length=70)),
                ('STUDENT_ID', models.IntegerField()),
                ('Student_roll_no', models.IntegerField()),
                ('NAME', models.CharField(max_length=70)),
                ('NAME_OF_ADVISOR', models.CharField(max_length=70)),
                ('MAIL', models.CharField(max_length=70)),
                ('APPROVED_BY', models.CharField(max_length=70)),
                ('SESSION', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='BTCSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_NO', models.IntegerField()),
                ('Course', models.CharField(max_length=70)),
                ('STUDENT_ID', models.IntegerField()),
                ('Student_roll_no', models.IntegerField()),
                ('NAME', models.CharField(max_length=70)),
                ('NAME_OF_ADVISOR', models.CharField(max_length=70)),
                ('MAIL', models.CharField(max_length=70)),
                ('APPROVED_BY', models.CharField(max_length=70)),
                ('SESSION', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='MBA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_NO', models.IntegerField()),
                ('Course', models.CharField(max_length=70)),
                ('STUDENT_ID', models.IntegerField()),
                ('Student_roll_no', models.IntegerField()),
                ('NAME', models.CharField(max_length=70)),
                ('NAME_OF_ADVISOR', models.CharField(max_length=70)),
                ('MAIL', models.CharField(max_length=70)),
                ('APPROVED_BY', models.CharField(max_length=70)),
                ('SESSION', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='MTECH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_NO', models.IntegerField()),
                ('Course', models.CharField(max_length=70)),
                ('STUDENT_ID', models.IntegerField()),
                ('Student_roll_no', models.IntegerField()),
                ('NAME', models.CharField(max_length=70)),
                ('NAME_OF_ADVISOR', models.CharField(max_length=70)),
                ('MAIL', models.CharField(max_length=70)),
                ('APPROVED_BY', models.CharField(max_length=70)),
                ('SESSION', models.CharField(max_length=70)),
            ],
        ),
    ]
