# Generated by Django 4.0.3 on 2022-04-11 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBTEST', '0002_admin_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_no', models.IntegerField()),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('work', models.CharField(max_length=70)),
                ('address', models.CharField(max_length=70)),
                ('county', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=70)),
                ('Worker_id', models.CharField(max_length=70)),
                ('Salary', models.IntegerField()),
                ('Age', models.IntegerField()),
            ],
        ),
    ]
